---
# handlers file for jpnewman.locale-timezone
- name: update tzdata
  command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

- name: restart crond
  service:
    name: cron
    state: restarted
